In [29]:
import pandas as pd
import pycountry

In [30]:
def normalize_country(name):
    if pd.isna(name):
        return "XX"

    # Clean up whitespace and force upper case for comparison
    name_clean = str(name).strip()

    try:
        # Look up by name, alpha_3 (USA), or alpha_2 (US)
        country = pycountry.countries.lookup(name_clean)
        return country.alpha_2  # Returns the 2-letter uppercase code
    except LookupError:
        # If pycountry can't find a match, default to XX
        return "XX"

In [73]:
def transform_data(df):

    # Identify malformed / quarantined rows
    # Critical fields that MUST be parseable to be considered a valid row
    parsed_event_time = pd.to_datetime(df['event_time'], errors='coerce', utc=True)
    parsed_ingested_at = pd.to_datetime(df['ingested_at'], errors='coerce', utc=True)
    
    # Definition of a bad/malformed row:
    # - Missing event_id
    # - Completely unparseable timestamps (NaT)
    is_malformed = (
        df['event_id'].isna() | 
        parsed_event_time.isna() | 
        parsed_ingested_at.isna()
    )

    # Separate good rows from quarantined rows
    df_quarantine = df[is_malformed].copy()
    df_clean = df[~is_malformed].copy()

    # revenue_usd as a float; unparseable and empty values become 0.0, but count them and report the count
    cleaned_strings = (
        df_clean["revenue_usd"].astype(str).str.replace(",", ".").str.strip()
    )

    convert_dt = pd.to_numeric(cleaned_strings, errors="coerce") #forcing unparseable text/empty values to NaN

    cnt_unparseable_or_empty = convert_dt.isna().sum()

    df_clean['revenue_usd'] = convert_dt.fillna(0.0)

    print(f"Found {cnt_unparseable_or_empty} unparseable or empty values")


    # country normalised to an upper-case two-letter code; anything you cannot map becomes 'XX'
    df_clean["country"] = df_clean["country"].apply(normalize_country)


    # timestamps parsed as timezone-aware UTC
    df_clean['event_time'] = pd.to_datetime(df_clean['event_time'], utc=True)
    df_clean['ingested_at'] = pd.to_datetime(df_clean['ingested_at'], utc=True)


    # test rows dropped
    df_clean = df_clean[df_clean['is_test'] == False]


    # duplicates resolved with the same rule as in task 2.1.
    df_clean = df_clean.sort_values(by = ['event_id', 'ingested_at'], ascending = [True, True])

    df_clean = df_clean.drop_duplicates(subset=['event_id'], keep='last')

    print(f"Clean rows processed: {len(df_clean)} | Quarantined rows: {len(df_quarantine)}")
    return df_clean, df_quarantine

In [ ]:
file_path = '../data/events_raw.csv'

try:
    print(f"Loading data from {file_path}...")
    df_raw = pd.read_csv(file_path)
except Exception as e:
    print(f"Failed to read CSV: {e}")
    df_raw = pd.DataFrame()

if not df_raw.empty:
    df_clean_final, df_quarantine_final = transform_data(df_raw)

Loading data from ../data/events_raw.csv...
Found 182 unparseable or empty values
Clean rows processed: 187 | Quarantined rows: 0

In [77]:
df_clean_final

,event_id,user_id,app_id,event_name,event_time,ingested_at,country,media_source,campaign,revenue_usd,is_test
36,00623e64-4c8e-4367-8c73-d7af7413fc85,usr_f20f8639,app_101,registration,2026-09-01 06:14:50+00:00,2026-09-01 08:19:20+00:00,US,Facebook Ads,PP_AND_US_purchase_broad,0.00,False
164,00d7ded6-6545-4f8b-b85e-78012c130713,usr_41cd5213,app_401,install,2026-08-31 20:14:35+00:00,2026-09-03 03:54:44+00:00,US,Facebook Ads,BM_IOS_US_launch,0.00,False
137,018975dd-be2a-4d9d-9add-0733f2b9642a,usr_d60f097e,app_101,registration,2026-08-27 22:49:04+00:00,2026-08-27 22:49:39+00:00,US,organic,NaN,0.00,False
212,01b11584-7caa-4bea-9d4e-9d6ff503eb65,usr_81376ee9,app_201,install,2026-08-26 19:03:31+00:00,2026-09-01 08:58:23+00:00,US,organic,NaN,0.00,False
66,01c358e0-2e9f-4408-89bb-cb71a095bd5d,usr_d60f097e,app_101,install,2026-08-27 22:38:00+00:00,2026-08-27 22:40:43+00:00,US,organic,NaN,0.00,False
11,02643b20-2ce4-4afe-9bb4-46a49728585e,usr_b1cafebd,app_102,purchase,2026-09-02 04:20:46+00:00,2026-09-07 11:53:56+00:00,XX,organic,NaN,4.99,False
241,033bed1d-ef24-401a-98d5-b7ec298e33d9,usr_8b5e3449,app_102,purchase,2026-09-02 01:24:39+00:00,2026-09-06 10:49:52+00:00,MX,organic,NaN,4.99,False
201,0383200a-2589-443b-acdf-ef0edc267e93,usr_5c0c5047,app_201,purchase,2026-08-31 13:42:42+00:00,2026-08-31 16:54:50+00:00,US,organic,NaN,0.00,False
104,0530dad0-3452-4c81-9e0b-3799d9fe5a01,usr_796abe47,app_401,install,2026-08-31 09:01:28+00:00,2026-08-31 09:03:24+00:00,US,Facebook Ads,BM_IOS_US_launch,0.00,False
89,05426617-c18d-4bc3-9e90-932cf232ae34,usr_5c0c5047,app_201,subscription_start,2026-08-30 20:42:29+00:00,2026-09-01 23:06:59+00:00,US,organic,NaN,9.99,False
153,062005e5-0789-4ac3-b5f3-034225bc9045,usr_2ab75771,app_401,purchase,2026-08-31 13:03:07+00:00,2026-09-02 07:35:00+00:00,XX,organic,NaN,4.99,False
244,06bd99a8-f5ff-4bf5-a8a1-61d825b6d6b6,usr_41cd5213,app_401,session_start,2026-09-02 12:41:48+00:00,2026-09-02 14:20:43+00:00,US,Facebook Ads,BM_IOS_US_launch,0.00,False
192,08502556-0454-4fee-b4bf-99735e3dd4b7,usr_c319deb6,app_102,registration,2026-09-01 21:15:16+00:00,2026-09-01 21:36:39+00:00,IN,organic,NaN,0.00,False
37,08c330a6-3b60-45bd-a811-b92f6e942ac3,usr_3f86062a,app_102,install,2026-08-31 09:33:05+00:00,2026-08-31 09:34:13+00:00,CA,organic,NaN,0.00,False
157,09e71313-d8f6-4945-b66f-06cd9e9100a5,usr_3f86062a,app_102,session_start,2026-09-02 02:33:36+00:00,2026-09-08 12:02:48+00:00,CA,organic,NaN,0.00,False
21,0a0603af-6d89-4d69-9223-30f3f912cd0d,usr_f6fe94f7,app_101,tutorial_complete,2026-08-30 15:42:27+00:00,2026-08-30 17:29:21+00:00,IN,applovin_int,PP_AND_AL_IN_cpi,0.00,False
71,0b2136f0-44d9-42f7-a149-bbf1861627a7,usr_cd6e0d25,app_401,purchase,2026-08-30 19:41:31+00:00,2026-08-30 19:43:35+00:00,TR,organic,NaN,4.99,False
119,0bacc1f9-3473-40cb-86ab-b71279b482c7,usr_8b5e3449,app_102,purchase,2026-09-02 07:20:06+00:00,2026-09-03 03:04:59+00:00,MX,organic,NaN,0.99,False
248,0bc5d801-6eb7-43ee-b68b-189efccdbd03,usr_c12a534e,app_401,tutorial_complete,2026-08-30 13:54:51+00:00,2026-08-30 13:56:26+00:00,US,organic,NaN,0.00,False
160,0d70134c-b29e-4f2a-9b34-75bfa0b28d9e,usr_7f50b2a8,app_102,registration,2026-09-03 15:34:29+00:00,2026-09-03 15:36:53+00:00,DE,tiktokglobal_int,PP_IOS_TT_DE_video,0.00,False
126,0e21fd0c-72df-44d7-a508-ad4813cf4cee,usr_ec2c2920,app_101,install,2026-08-26 00:13:26+00:00,2026-08-26 00:14:44+00:00,US,Facebook Ads,PP_AND_US_purchase_broad,0.00,False
90,107dfbda-4fda-4d77-988e-9969e1ea02a8,usr_2c9a69ca,app_101,tutorial_complete,2026-08-28 20:03:00+00:00,2026-08-28 20:03:59+00:00,US,googleadwords_int,PP_AND_UAC_tier1,0.00,False
195,10b89bd5-e622-49a9-bf69-aa271e9c34d0,usr_c319deb6,app_102,session_start,2026-09-02 08:33:11+00:00,2026-09-02 09:48:35+00:00,IN,organic,NaN,0.00,False
151,10ea0da4-f7e4-42ea-b38a-06af809d815d,usr_796abe47,app_401,registration,2026-08-31 09:08:37+00:00,2026-08-31 09:13:27+00:00,US,Facebook Ads,BM_IOS_US_launch,0.00,False
209,11916c3f-40cc-4d8c-bba1-9a637cecb016,usr_c12a534e,app_401,registration,2026-08-30 13:42:55+00:00,2026-08-30 13:43:10+00:00,US,organic,NaN,0.00,False
138,126c9d53-4c1a-4652-b7f1-3913e2d1f19e,usr_4e87df20,app_401,session_start,2026-08-31 15:19:44+00:00,2026-08-31 15:24:20+00:00,DE,organic,NaN,0.00,False
168,13f305c0-c272-4802-b2a2-c71f21b776e4,usr_bd5ddbff,app_101,session_start,2026-08-30 23:28:24+00:00,2026-08-31 00:22:06+00:00,XX,googleadwords_int,PP_AND_UAC_tier1,0.00,False
231,14a2ac19-bdca-4474-9ec2-d30025b93547,usr_20199239,app_102,purchase,2026-09-04 21:08:49+00:00,2026-09-04 21:11:29+00:00,ES,organic,NaN,0.99,False
171,156da01d-1856-4312-8993-1a329d73c874,usr_f6fe94f7,app_101,install,2026-08-30 15:14:31+00:00,2026-09-01 19:55:42+00:00,IN,applovin_int,PP_AND_AL_IN_cpi,0.00,False
106,1671b022-bcbc-4763-a42c-3ad7b7603d83,usr_1563250a,app_401,subscription_start,2026-08-30 07:22:31+00:00,2026-09-01 00:00:55+00:00,JP,organic,NaN,0.00,False
22,19903189-008f-4f1b-bf77-fcf045f87de1,usr_3fbfe452,app_101,session_start,2026-08-30 23:53:44+00:00,2026-08-31 00:38:38+00:00,XX,Facebook Ads,PP_AND_US_purchase_broad,0.00,False
118,1a287297-bdd2-410e-b1da-99f5a187193f,usr_d5d352ef,app_201,session_start,2026-08-29 14:03:35+00:00,2026-08-29 14:06:05+00:00,CA,organic,NaN,0.00,False
158,1a5b2e96-188f-4c73-961f-092b1c4b3fa2,usr_bd5ddbff,app_101,install,2026-08-27 20:22:17+00:00,2026-08-27 20:23:40+00:00,US,googleadwords_int,PP_AND_UAC_tier1,0.00,False
247,1aeff6a5-7b58-4d6a-b2df-efd1cd49e713,usr_7f50b2a8,app_102,install,2026-09-03 15:20:43+00:00,2026-09-03 15:20:51+00:00,DE,tiktokglobal_int,PP_IOS_TT_DE_video,0.00,False
107,1d63c3dd-3efc-4e2b-84ca-0c8d2b90083e,usr_9ff95e01,app_101,purchase,2026-09-03 06:09:25+00:00,2026-09-03 06:09:55+00:00,IN,applovin_int,PP_AND_AL_IN_cpi,1.99,False
5,1edaa205-45fa-49cd-97f8-2e98ae0697ea,usr_f20f8639,app_101,install,2026-09-01 06:09:46+00:00,2026-09-01 06:14:38+00:00,US,Facebook Ads,PP_AND_US_purchase_broad,0.00,False
88,2152e611-43be-41ad-bf3b-3b79730981e4,usr_8b5e3449,app_102,registration,2026-09-01 13:13:24+00:00,2026-09-04 08:19:29+00:00,MX,organic,NaN,0.00,False
156,21b71716-1fbe-409f-ad23-66d0ef2227d0,usr_b1cafebd,app_102,session_start,2026-09-01 03:46:48+00:00,2026-09-01 03:50:40+00:00,US,organic,NaN,0.00,False
28,21c5ef9a-378f-4b01-b01a-c8b1b0711cf8,usr_41cd5213,app_401,session_start,2026-09-01 10:15:08+00:00,2026-09-01 10:19:18+00:00,US,Facebook Ads,BM_IOS_US_launch,0.00,False
214,232639fc-9808-4b47-ad4b-5fadd61b263e,usr_3fbfe452,app_101,purchase,2026-08-28 14:35:09+00:00,2026-08-29 00:15:26+00:00,US,Facebook Ads,PP_AND_US_purchase_broad,9.99,False
149,24cf4b00-e29d-49c6-9794-063e1deba994,usr_ec2c2920,app_101,purchase,2026-08-26 02:26:07+00:00,2026-08-26 02:42:08+00:00,US,Facebook Ads,PP_AND_US_purchase_broad,0.00,False
213,27c9afcc-617f-447c-b72d-11a77f7f6963,usr_bfac162d,app_101,install,2026-09-02 16:53:13+00:00,2026-09-02 18:57:22+00:00,XX,Facebook Ads,PP_AND_US_purchase_broad,0.00,False
111,28ddc12b-9aff-4540-aa4b-ad8f8f4cba16,usr_d5d352ef,app_201,session_start,2026-08-27 18:09:46+00:00,2026-08-27 18:13:58+00:00,CA,organic,NaN,0.00,False
135,29a1c527-ab86-404d-ad40-27d39d3a05bd,usr_063a1417,app_201,install,2026-08-29 12:54:04+00:00,2026-08-29 23:18:50+00:00,BR,organic,NaN,0.00,False
8,2b560805-ebd6-45ac-827b-231f34dadbd0,usr_81376ee9,app_201,subscription_start,2026-08-27 00:08:24+00:00,2026-08-27 00:09:52+00:00,US,organic,NaN,6.99,False
217,2c628c22-2e5d-41f7-8724-2d565b783fb6,usr_8b5e3449,app_102,tutorial_complete,2026-09-01 13:31:01+00:00,2026-09-01 13:31:26+00:00,MX,organic,NaN,0.00,False
105,31a8a3f3-223f-4ed5-9652-c698a5096136,usr_d5d352ef,app_201,session_start,2026-08-31 15:42:43+00:00,2026-09-01 05:32:01+00:00,CA,organic,NaN,0.00,False
191,32323553-1b9a-4eb2-9df0-c17f4b297f50,usr_ac5b47cb,app_101,install,2026-09-04 20:49:22+00:00,2026-09-04 20:52:51+00:00,XX,Facebook Ads,PP_AND_US_purchase_broad,0.00,False
203,32dcdfb8-95a3-43da-9784-c3840248e24b,usr_81376ee9,app_201,purchase,2026-08-28 11:35:07+00:00,2026-08-28 11:37:44+00:00,US,organic,NaN,2.99,False
233,348b0dcd-9c99-4769-b25f-c1c8508b65d6,usr_bfac162d,app_101,registration,2026-09-02 17:07:52+00:00,2026-09-04 03:22:27+00:00,US,Facebook Ads,PP_AND_US_purchase_broad,0.00,False
14,348d0878-3ca9-4018-ba79-b6ea16d15896,usr_81376ee9,app_201,purchase,2026-08-26 19:17:37+00:00,2026-08-26 19:21:32+00:00,US,organic,NaN,4.99,False
15,390ffc3d-2e6e-4f72-adda-e645859681ef,usr_4e87df20,app_401,registration,2026-08-31 11:08:08+00:00,2026-08-31 11:09:05+00:00,XX,organic,NaN,0.00,False
16,3b8c05a5-0cec-4a31-ac58-2c17aa135138,usr_c12a534e,app_401,session_start,2026-08-31 15:37:51+00:00,2026-08-31 15:40:02+00:00,XX,organic,NaN,0.00,False
210,3dca75e7-ab5e-46a4-8fd8-b8733aeedb98,usr_cd6e0d25,app_401,install,2026-08-29 10:26:49+00:00,2026-08-29 10:29:56+00:00,TR,organic,NaN,0.00,False
174,3e8a4f55-1315-4120-870f-06d085409417,usr_2ab75771,app_401,session_start,2026-09-01 05:17:03+00:00,2026-09-01 05:31:19+00:00,DE,organic,NaN,0.00,False
178,405602b0-c8c6-4cd6-8d61-74576b6b7732,usr_4626ffa7,app_101,session_start,2026-09-04 22:55:33+00:00,2026-09-04 22:57:24+00:00,US,Facebook Ads,PP_AND_US_purchase_broad,0.00,False
57,41da141c-9340-408e-a82b-a9dbc297be50,usr_bb23afa6,app_201,session_start,2026-09-01 00:00:00+00:00,2026-09-01 00:00:04+00:00,NG,unityads_int,FP_IOS_UNITY_NG_cpi,0.00,False
236,42bbae22-c40e-45a3-b957-43f555ae2c79,usr_2c9a69ca,app_101,registration,2026-08-28 19:49:46+00:00,2026-08-28 21:16:34+00:00,US,googleadwords_int,PP_AND_UAC_tier1,0.00,False
133,4367c393-573d-41de-b7af-debd5fc9bef1,usr_3fbfe452,app_101,install,2026-08-27 22:34:56+00:00,2026-08-28 01:58:23+00:00,XX,Facebook Ads,PP_AND_US_purchase_broad,0.00,False
230,43abc360-4f3b-427a-891e-b3e1e3b3adec,usr_b1cafebd,app_102,install,2026-08-30 12:59:00+00:00,2026-08-30 13:03:30+00:00,US,organic,NaN,0.00,False
80,45ada3a9-1d68-4104-affe-7379616d9976,usr_f6fe94f7,app_101,registration,2026-08-30 15:24:58+00:00,2026-09-01 07:08:02+00:00,IN,applovin_int,PP_AND_AL_IN_cpi,0.00,False
41,48d68b0a-4acb-4e13-a067-d7d54b7fa910,usr_b1cafebd,app_102,purchase,2026-09-02 15:28:27+00:00,2026-09-02 15:29:26+00:00,US,organic,NaN,9.99,False
140,494f6f57-1e4e-4d43-b459-b1c08412df88,usr_8b5e3449,app_102,session_start,2026-09-02 11:29:12+00:00,2026-09-02 11:30:20+00:00,MX,organic,NaN,0.00,False
63,4a4f7611-e189-473a-be59-4a4a84444f03,usr_9c608926,app_101,purchase,2026-08-28 15:20:51+00:00,2026-08-29 22:59:29+00:00,CA,organic,NaN,19.99,False
117,4b6f81f1-2e40-48e0-bfa7-9c52e9d45983,usr_ff2065b7,app_201,install,2026-08-28 22:29:24+00:00,2026-08-28 22:32:49+00:00,US,organic,NaN,0.00,False
147,4d5d3365-7f29-4de5-948d-6bfc81071cae,usr_5c975c2e,app_201,session_start,2026-08-30 23:39:37+00:00,2026-08-31 00:23:52+00:00,XX,organic,NaN,0.00,False
246,4e8249d7-e89b-4c8f-9f04-ba23a7da7843,usr_b34c3bec,app_401,install,2026-09-04 00:13:26+00:00,2026-09-04 00:17:45+00:00,US,organic,NaN,0.00,False
215,506057d2-01a2-450d-98a2-840dcfa1dc62,usr_2ab75771,app_401,install,2026-08-30 18:02:57+00:00,2026-08-30 21:10:18+00:00,XX,organic,NaN,0.00,False
232,51315e20-5a6f-4da8-a485-78b88594c60f,usr_81376ee9,app_201,session_start,2026-08-28 06:49:23+00:00,2026-08-28 06:52:27+00:00,XX,organic,NaN,0.00,False
2,521879fd-2c91-48d1-a844-8f4b53457829,usr_7021be3c,app_101,purchase,2026-08-29 17:37:10+00:00,2026-08-29 18:43:09+00:00,JP,organic,NaN,0.99,False
27,52e2d4a6-3c82-48e4-bdd6-503c3d168b87,usr_5c0c5047,app_201,registration,2026-08-30 14:09:13+00:00,2026-08-30 14:11:04+00:00,US,organic,NaN,0.00,False
243,53740765-5136-4fe0-b8ab-9a8edfa46551,usr_1563250a,app_401,install,2026-08-29 12:12:27+00:00,2026-08-29 13:09:59+00:00,JP,organic,NaN,0.00,False
205,56568ba4-77e7-425f-acb3-6bfff5d17c88,usr_2ab75771,app_401,purchase,2026-08-31 08:50:17+00:00,2026-08-31 19:41:49+00:00,DE,organic,NaN,4.99,False
206,56fb37a8-dd81-4cbe-8179-c1a2a331873f,usr_d702c8df,app_201,registration,2026-09-04 15:15:47+00:00,2026-09-04 15:20:18+00:00,IN,organic,NaN,0.00,False
190,5813987b-92c1-4c2d-af72-c85372789150,usr_4626ffa7,app_101,tutorial_complete,2026-09-03 17:11:53+00:00,2026-09-03 17:12:03+00:00,US,Facebook Ads,PP_AND_US_purchase_broad,0.00,False
161,59f13637-357f-4787-a67d-133397ecae5b,usr_4e87df20,app_401,install,2026-08-31 11:06:41+00:00,2026-08-31 12:31:58+00:00,DE,organic,NaN,0.00,False
1,5d99e246-293f-4027-971c-3522f84babb1,usr_7dafbb4c,app_401,session_start,2026-09-04 14:15:31+00:00,2026-09-04 14:35:41+00:00,US,Facebook Ads,BM_IOS_US_launch,0.00,False
199,5f2724c5-99fc-4c5e-b89f-f9650961af3d,usr_7021be3c,app_101,session_start,2026-08-31 23:59:59+00:00,2026-09-01 02:43:53+00:00,JP,organic,NaN,0.00,False
75,5f700c4a-6932-4c29-8423-1c97618b8112,usr_b34c3bec,app_401,tutorial_complete,2026-09-04 00:24:11+00:00,2026-09-04 00:25:53+00:00,US,organic,NaN,0.00,False
55,5f88dc65-d64c-44c5-b737-e43dc5816e2d,usr_a4ab2303,app_201,registration,2026-08-27 18:43:15+00:00,2026-08-27 18:46:10+00:00,US,unityads_int,FP_IOS_UNITY_NG_cpi,0.00,False
125,6384d4c1-df1b-403b-ba91-dd8a3001154f,usr_41cd5213,app_401,registration,2026-08-31 20:15:57+00:00,2026-08-31 23:36:53+00:00,US,Facebook Ads,BM_IOS_US_launch,0.00,False
173,642c2ca7-10bf-47c4-8e66-cc57451c063d,usr_20199239,app_102,install,2026-09-04 11:38:56+00:00,2026-09-04 13:40:20+00:00,ES,organic,NaN,0.00,False
194,663fc056-d441-44cc-aa7a-16a93cf929de,usr_bb23afa6,app_201,install,2026-08-30 12:29:23+00:00,2026-08-30 17:06:55+00:00,NG,unityads_int,FP_IOS_UNITY_NG_cpi,0.00,False
177,6672b0cc-46f5-4797-a953-d97db77416f5,usr_ff2065b7,app_201,registration,2026-08-28 22:32:52+00:00,2026-08-29 02:13:01+00:00,US,organic,NaN,0.00,False
100,67e18849-a8b3-4144-b18c-43fad17f3d8b,usr_8b5e3449,app_102,session_start,2026-09-01 20:12:51+00:00,2026-09-01 20:13:01+00:00,XX,organic,NaN,0.00,False
78,67f374da-2642-447e-baa9-46bc7c31d2f8,usr_e647bc94,app_201,registration,2026-08-29 20:30:30+00:00,2026-08-29 20:31:19+00:00,TR,organic,NaN,0.00,False
224,6817fb2d-81a1-41ae-b546-0275e576be4b,usr_9ff95e01,app_101,install,2026-08-29 13:09:10+00:00,2026-08-29 13:10:34+00:00,IN,applovin_int,PP_AND_AL_IN_cpi,0.00,False
144,69a00cdf-1e11-42c5-a951-bc9796bf3646,usr_c59002f3,app_101,session_start,2026-09-01 20:53:13+00:00,2026-09-02 12:04:31+00:00,US,Facebook Ads,PP_AND_US_purchase_broad,0.00,False
96,69b8ab08-7391-47f0-a1f9-e4fa91da4db3,usr_b1cafebd,app_102,tutorial_complete,2026-08-30 13:32:15+00:00,2026-08-30 17:56:46+00:00,US,organic,NaN,0.00,False
245,69e67e43-4ab4-4779-a064-c958ee5eecd1,usr_9c608926,app_101,purchase,2026-08-31 10:14:20+00:00,2026-08-31 10:19:00+00:00,CA,organic,NaN,1.99,False
228,6a612f6a-098b-4518-80ba-475b6309a67c,usr_ec2c2920,app_101,session_start,2026-08-31 23:13:43+00:00,2026-08-31 23:16:15+00:00,US,Facebook Ads,PP_AND_US_purchase_broad,0.00,False
61,6c2bf8d1-eaca-4a77-bb91-0905dee84e1d,usr_41cd5213,app_401,purchase,2026-09-02 05:59:11+00:00,2026-09-02 16:41:21+00:00,US,Facebook Ads,BM_IOS_US_launch,9.99,False
6,6d3c9beb-6fdc-4347-952a-e588472d3ad9,usr_2ab75771,app_401,tutorial_complete,2026-08-30 18:22:49+00:00,2026-08-30 18:23:21+00:00,XX,organic,NaN,0.00,False
219,6e6fddc0-5e28-458f-acdd-2806af2bde29,usr_e647bc94,app_201,purchase,2026-09-01 05:48:52+00:00,2026-09-01 18:08:47+00:00,TR,organic,NaN,2.99,False
53,6f90877f-c513-4ea1-89db-e3fd556846bd,usr_d702c8df,app_201,install,2026-09-04 15:05:17+00:00,2026-09-04 16:27:55+00:00,IN,organic,NaN,0.00,False
239,6fadd05b-5d22-405d-b756-ed5242536ba2,usr_cd6e0d25,app_401,tutorial_complete,2026-08-29 10:44:26+00:00,2026-08-29 10:48:25+00:00,TR,organic,NaN,0.00,False
76,706d376f-df1c-4553-b8cb-9d0b7cb7fb92,usr_5c975c2e,app_201,registration,2026-08-27 18:18:34+00:00,2026-08-27 18:19:43+00:00,GB,organic,NaN,0.00,False
19,71cce240-ce0a-4509-81f3-5eba8d0f1ef1,usr_08f8511e,app_201,registration,2026-08-31 05:58:34+00:00,2026-08-31 08:20:14+00:00,NG,unityads_int,FP_IOS_UNITY_NG_cpi,0.00,False
110,7334bfed-7088-43e7-8c38-f9818ec94575,usr_fae17389,app_101,install,2026-08-26 21:01:53+00:00,2026-08-27 10:06:57+00:00,US,Facebook Ads,PP_AND_US_purchase_broad,0.00,False
40,74c9b276-2354-4c04-a8a1-56d0d4653a61,usr_ec2c2920,app_101,tutorial_complete,2026-08-26 00:36:35+00:00,2026-08-26 00:38:18+00:00,US,Facebook Ads,PP_AND_US_purchase_broad,0.00,False
31,782bfaab-cd8b-4e76-a61b-38cc703cd6a2,usr_046400f2,app_201,install,2026-09-02 10:03:31+00:00,2026-09-02 10:06:36+00:00,NG,unityads_int,FP_IOS_UNITY_NG_cpi,0.00,False
98,786c38f6-d691-4ab3-8773-13846102bffe,usr_d5d352ef,app_201,session_start,2026-08-30 05:01:41+00:00,2026-09-02 20:55:15+00:00,CA,organic,NaN,0.00,False
108,79a358d7-914f-49ab-98b9-8346a3cbc2b6,usr_d5d352ef,app_201,install,2026-08-27 17:37:40+00:00,2026-08-27 17:38:45+00:00,CA,organic,NaN,0.00,False
39,7a10a1da-ebad-49f1-a57b-58057f098752,usr_cd6e0d25,app_401,registration,2026-08-29 10:28:18+00:00,2026-08-29 10:28:34+00:00,TR,organic,NaN,0.00,False
72,7b3463ac-977a-471f-93de-6a465622eb41,usr_7f50b2a8,app_102,session_start,2026-09-03 16:14:32+00:00,2026-09-06 04:23:20+00:00,DE,tiktokglobal_int,PP_IOS_TT_DE_video,0.00,False
208,7c979346-43bc-4a3d-8429-35d0e3c2730c,usr_ac5b47cb,app_101,registration,2026-09-04 20:55:13+00:00,2026-09-04 20:57:15+00:00,US,Facebook Ads,PP_AND_US_purchase_broad,0.00,False
237,7cb1dd54-0a6a-45c1-95c7-9508a2e6aa9a,usr_9c608926,app_101,registration,2026-08-28 12:57:44+00:00,2026-08-28 13:09:19+00:00,CA,organic,NaN,0.00,False
139,7d7e3878-7ade-4b43-a7f9-904b75451b69,usr_81376ee9,app_201,session_start,2026-08-29 23:27:37+00:00,2026-08-29 23:30:16+00:00,US,organic,NaN,0.00,False
198,7dbfa7e6-ea44-41d6-a388-e64932597331,usr_4626ffa7,app_101,registration,2026-09-03 16:52:45+00:00,2026-09-03 16:54:42+00:00,US,Facebook Ads,PP_AND_US_purchase_broad,0.00,False
196,7e29bbf9-e7f7-46e9-904b-09d7e5bf710f,usr_c12a534e,app_401,install,2026-08-30 13:39:01+00:00,2026-09-01 12:13:40+00:00,US,organic,NaN,0.00,False
152,80ea5766-aaf6-494d-94b7-2095e00c0e4b,usr_8b5e3449,app_102,session_start,2026-09-02 07:19:42+00:00,2026-09-02 07:23:34+00:00,MX,organic,NaN,0.00,False
59,81c1c2e5-8369-4e08-98c4-618386a69a92,usr_b1cafebd,app_102,registration,2026-08-30 13:12:50+00:00,2026-08-30 13:13:11+00:00,US,organic,NaN,0.00,False
238,836e8205-ecac-4af7-9934-b6356384c1fb,usr_ec2c2920,app_101,registration,2026-08-26 00:21:51+00:00,2026-08-26 00:21:52+00:00,US,Facebook Ads,PP_AND_US_purchase_broad,0.00,False
30,8398f683-d10c-4ed1-9bf5-f8fb4b6ea08c,usr_7021be3c,app_101,tutorial_complete,2026-08-28 14:33:55+00:00,2026-08-28 18:20:02+00:00,JP,organic,NaN,0.00,False
169,8574e7bc-dfaa-474d-9ffb-44707d1c0bf5,usr_fa31fad2,app_201,install,2026-08-29 19:03:54+00:00,2026-08-29 22:01:02+00:00,US,Facebook Ads,FP_IOS_US_trial,0.00,False
227,87b26240-9197-4386-9ed5-fa09e7fb264b,usr_fae17389,app_101,registration,2026-08-26 21:04:14+00:00,2026-08-26 21:14:08+00:00,US,Facebook Ads,PP_AND_US_purchase_broad,0.00,False
145,893ed296-80ac-47d1-be67-302c902d09e7,usr_4626ffa7,app_101,session_start,2026-09-04 02:33:25+00:00,2026-09-04 02:38:13+00:00,US,Facebook Ads,PP_AND_US_purchase_broad,0.00,False
20,89758a9e-f821-4460-9ba6-d28854475789,usr_7021be3c,app_101,install,2026-08-28 14:09:09+00:00,2026-08-28 14:20:15+00:00,JP,organic,NaN,0.00,False
180,8b958e46-ccf4-4536-b73b-f69c96fe17cb,usr_5c975c2e,app_201,session_start,2026-08-28 00:56:57+00:00,2026-08-28 01:01:25+00:00,GB,organic,NaN,0.00,False
69,93b98204-9caf-48cd-b155-84689c7fb498,usr_9e5e8452,app_101,install,2026-09-01 22:05:13+00:00,2026-09-01 22:07:37+00:00,US,Facebook Ads,PP_AND_US_purchase_broad,0.00,False
60,94d7343f-3c62-4be3-a819-f0e0347c6667,usr_bb23afa6,app_201,tutorial_complete,2026-08-30 12:37:59+00:00,2026-08-30 12:40:11+00:00,NG,unityads_int,FP_IOS_UNITY_NG_cpi,0.00,False
218,9ad85796-b5c2-4318-822f-4872676968cd,usr_b0d3afb2,app_102,registration,2026-08-31 01:53:48+00:00,2026-09-01 22:11:03+00:00,XX,tiktokglobal_int,PP_IOS_TT_DE_video,0.00,False
200,9d75f47a-978d-4a7a-9b1f-b3251e6e2576,usr_5c975c2e,app_201,install,2026-08-27 18:07:05+00:00,2026-08-27 18:08:35+00:00,GB,organic,NaN,0.00,False

In [78]:
df_quarantine_final

Empty DataFrame
Columns: [event_id, user_id, app_id, event_name, event_time, ingested_at, country, media_source, campaign, revenue_usd, is_test]
Index: []